### ISSUE TITLE
Changing the instance name after setup causes `Cannot read properties of undefined` error

### ISSUE THREAD

**Issue by AndreasHassler-cnic** [lukasbestle/kirby-versions#12]
## Describe the bug
I wanted to change the name for the local-instance to Staging (like described here: https://github.com/lukasbestle/kirby-versions/wiki/Configuration)

## Steps to reproduce

Add this to configuration:

```
'lukasbestle.versions' => [
        'instances' => [

            'Live' => [
                'contentRoot' => $base . '/content',
                'color' => '#DC143C'
            ],
        ]
    ]
```
![Screenshot_20221115_085108](https://user-images.githubusercontent.com/105478765/201860822-b9f8ff4e-fd37-40bc-ba82-a21ea254152f.png)

This works as expected, but I would like to rename Local to Staging.

Change configuration to this: 

```
'lukasbestle.versions' => [
        'instances' => [

            'Live' => [
                'contentRoot' => $base . '/content',
                'color' => '#DC143C'
            ],
            'Staging' => [
                'contentRoot' => $base . '/content-preview',
                'color' => '#f5871f'
            ],
    ]
 ]

```

![Screenshot_20221115_085419](https://user-images.githubusercontent.com/105478765/201861279-faece8a0-5e98-4361-a977-987a4ca7274c.png)

## Technical details

- Plugin version: 1.0.4
- Kirby version: 3.7.5.1
- Browser: Chrome
- Server operating system: Ubuntu
- `git --version` **on the server**: 2.30.2

**Comment by lukasbestle** [comment]
Thank you for your bug report.

So far I unfortunately cannot reproduce the issue. I believe that the issue comes from a failed lookup within the "Versions" table. Unfortunately the error message is displayed right over the instance name tags, but probably the tags are rendered incompletely or not at all.

I have a few questions:

- Does the issue persist if you reload the Versions view or clear your browser cache?
- Could you please check the contents of the API response from `GET /api/versions`? If it doesn't contain confidential data, posting it here would help a lot to debug the issue.

**Comment by AndreasHassler-cnic** [comment]
Hi Lucas,

thanks for your response.
The isue still persists even after reloading or clearing the cache.

Here is the output of the api-call:

```
{
  "instances": {
    "Live": {
      "changes": [],
      "color": "#DC143C",
      "isCurrent": false,
      "name": "Live",
      "version": "20221121_003",
      "versionLabel": ".IO Promotion correction"
    },
    "Staging": {
      "changes": [],
      "color": "#547b82",
      "isCurrent": true,
      "name": "Staging",
      "version": "20221121_003",
      "versionLabel": ".IO Promotion correction"
    }
  },
  "versions": {
    "20221121_003": {
      "created": 1669019884,
      "creatorEmail": "jon@doe.com",
      "creatorName": "Jon Doe",
      "instances": [
        "Live",
        "Staging"
      ],
      "label": ".IO Promotion correction",
      "name": "20221121_003",
      "originInstance": "Local"
    },
    "20221121_002": {
      "created": 1669019459,
      "creatorEmail": "jon@doe.com",
      "creatorName": "Jon Doe",
      "instances": [],
      "label": ".IO Promotion to promotion page",
      "name": "20221121_002",
      "originInstance": "Local"
    },
    "20221121_001": {
      "created": 1669018776,
      "creatorEmail": "jon@doe.com",
      "creatorName": "Jon Doe",
      "instances": [],
      "label": "Addition of IO Promo to Home (instead ME)",
      "name": "20221121_001",
      "originInstance": "Local"
    },
    "20221118_001": {
      "created": 1668776324,
      "creatorEmail": "jon@doe.com",
      "creatorName": "Jon Doe",
      "instances": [],
      "label": "Removed border from .org-logo",
      "name": "20221118_001",
      "originInstance": "Local"
    },
    "20221115_initial": {
      "created": null,
      "creatorEmail": null,
      "creatorName": null,
      "instances": [],
      "label": "removed lock",
      "name": "20221115_initial",
      "originInstance": null
    }
  }
}

```

**Comment by lukasbestle** [comment]
Ah, I suspect this happens because the instance was renamed after versions have already been created. Your versions link to an `originInstance` with the name "Local" (which is the built-in default). But this instance doesn't exist anymore and can therefore not be displayed correctly.

I will add a check for invalid instance names. In this case, the instance name will be displayed without the colored background. But at least there won't be a UI error.

A full fix can only be performed in your content Git repo by overwriting the Git tags with the custom instance name or deleting all versions that were created before the change.

**Comment by AndreasHassler-cnic** [comment]
Thank you

**Comment by lukasbestle** [comment]
✅
